# Generated by Django 2.2.5 on 2020-10-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_recommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
