# Generated by Django 2.2.5 on 2020-10-23 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201023_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('SPH', models.FloatField(max_length=30)),
                ('CYL', models.FloatField(max_length=30)),
                ('AXIS', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Powers',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='powers',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Power'),
        ),
    ]
