# Generated by Django 2.2.5 on 2020-10-24 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201024_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='cyl',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='power',
            name='sph',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='power',
            name='AXIS',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
