# Generated by Django 2.2.5 on 2020-10-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201024_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='AXIS',
        ),
        migrations.RemoveField(
            model_name='power',
            name='name',
        ),
    ]
