# Generated by Django 2.2.5 on 2020-10-24 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201024_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
