# Generated by Django 2.2.5 on 2020-10-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201024_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
